version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: typeo-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Add other backend environment variables here
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: typeo-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other frontend environment variables here
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: typeo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  mongo-data: 